// app/api/jurisdiction-filter/route.ts

import { type NextRequest, NextResponse } from "next/server"

// Complete jurisdictions data including countries, regions, and US states
const HARDCODED_JURISDICTIONS = [
  { id: 1, name: "Afghanistan", code: "AF", type: "country", iso3: "AFG" },
  { id: 2, name: "Albania", code: "AL", type: "country", iso3: "ALB" },
  { id: 3, name: "Algeria", code: "DZ", type: "country", iso3: "DZA" },
  { id: 4, name: "American Samoa", code: "AS", type: "country", iso3: "ASM" },
  { id: 5, name: "Andorra", code: "AD", type: "country", iso3: "AND" },
  { id: 6, name: "Angola", code: "AO", type: "country", iso3: "AGO" },
  { id: 7, name: "Anguilla", code: "AI", type: "country", iso3: "AIA" },
  { id: 8, name: "Antarctica", code: "AQ", type: "country", iso3: "ATA" },
  { id: 9, name: "Antigua and Barbuda", code: "AG", type: "country", iso3: "ATG" },
  { id: 10, name: "Argentina", code: "AR", type: "country", iso3: "ARG" },
  { id: 11, name: "Armenia", code: "AM", type: "country", iso3: "ARM" },
  { id: 12, name: "Aruba", code: "AW", type: "country", iso3: "ABW" },
  { id: 13, name: "Australia", code: "AU", type: "country", iso3: "AUS" },
  { id: 14, name: "Austria", code: "AT", type: "country", iso3: "AUT" },
  { id: 15, name: "Azerbaijan", code: "AZ", type: "country", iso3: "AZE" },
  { id: 16, name: "Bahamas", code: "BS", type: "country", iso3: "BHS" },
  { id: 17, name: "Bahrain", code: "BH", type: "country", iso3: "BHR" },
  { id: 18, name: "Bangladesh", code: "BD", type: "country", iso3: "BGD" },
  { id: 19, name: "Barbados", code: "BB", type: "country", iso3: "BRB" },
  { id: 20, name: "Belarus", code: "BY", type: "country", iso3: "BLR" },
  { id: 21, name: "Belgium", code: "BE", type: "country", iso3: "BEL" },
  { id: 22, name: "Belize", code: "BZ", type: "country", iso3: "BLZ" },
  { id: 23, name: "Benin", code: "BJ", type: "country", iso3: "BEN" },
  { id: 24, name: "Bermuda", code: "BM", type: "country", iso3: "BMU" },
  { id: 25, name: "Bhutan", code: "BT", type: "country", iso3: "BTN" },
  { id: 26, name: "Bolivia (Plurinational State of)", code: "BO", type: "country", iso3: "BOL" },
  { id: 27, name: "Bonaire, Sint Eustatius and Saba", code: "BQ", type: "country", iso3: "BES" },
  { id: 28, name: "Bosnia and Herzegovina", code: "BA", type: "country", iso3: "BIH" },
  { id: 29, name: "Botswana", code: "BW", type: "country", iso3: "BWA" },
  { id: 30, name: "Bouvet Island", code: "BV", type: "country", iso3: "BVT" },
  { id: 31, name: "Brazil", code: "BR", type: "country", iso3: "BRA" },
  { id: 32, name: "British Indian Ocean Territory", code: "IO", type: "country", iso3: "IOT" },
  { id: 33, name: "Brunei Darussalam", code: "BN", type: "country", iso3: "BRN" },
  { id: 34, name: "Bulgaria", code: "BG", type: "country", iso3: "BGR" },
  { id: 35, name: "Burkina Faso", code: "BF", type: "country", iso3: "BFA" },
  { id: 36, name: "Burundi", code: "BI", type: "country", iso3: "BDI" },
  { id: 37, name: "Cabo Verde", code: "CV", type: "country", iso3: "CPV" },
  { id: 38, name: "Cambodia", code: "KH", type: "country", iso3: "KHM" },
  { id: 39, name: "Cameroon", code: "CM", type: "country", iso3: "CMR" },
  { id: 40, name: "Canada", code: "CA", type: "country", iso3: "CAN" },
  { id: 41, name: "Cayman Islands", code: "KY", type: "country", iso3: "CYM" },
  { id: 42, name: "Central African Republic", code: "CF", type: "country", iso3: "CAF" },
  { id: 43, name: "Chad", code: "TD", type: "country", iso3: "TCD" },
  { id: 44, name: "Chile", code: "CL", type: "country", iso3: "CHL" },
  { id: 45, name: "China", code: "CN", type: "country", iso3: "CHN" },
  { id: 46, name: "Christmas Island", code: "CX", type: "country", iso3: "CXR" },
  { id: 47, name: "Cocos (Keeling) Islands", code: "CC", type: "country", iso3: "CCK" },
  { id: 48, name: "Colombia", code: "CO", type: "country", iso3: "COL" },
  { id: 49, name: "Comoros", code: "KM", type: "country", iso3: "COM" },
  { id: 50, name: "Democratic Republic of the Congo", code: "CD", type: "country", iso3: "COD" },
  { id: 51, name: "Congo", code: "CG", type: "country", iso3: "COG" },
  { id: 52, name: "Cook Islands", code: "CK", type: "country", iso3: "COK" },
  { id: 53, name: "Costa Rica", code: "CR", type: "country", iso3: "CRI" },
  { id: 54, name: "Croatia", code: "HR", type: "country", iso3: "HRV" },
  { id: 55, name: "Cuba", code: "CU", type: "country", iso3: "CUB" },
  { id: 56, name: "Curaçao", code: "CW", type: "country", iso3: "CUW" },
  { id: 57, name: "Cyprus", code: "CY", type: "country", iso3: "CYP" },
  { id: 58, name: "Czechia", code: "CZ", type: "country", iso3: "CZE" },
  { id: 59, name: "Côte d'Ivoire", code: "CI", type: "country", iso3: "CIV" },
  { id: 60, name: "Denmark", code: "DK", type: "country", iso3: "DNK" },
  { id: 61, name: "Djibouti", code: "DJ", type: "country", iso3: "DJI" },
  { id: 62, name: "Dominica", code: "DM", type: "country", iso3: "DMA" },
  { id: 63, name: "Dominican Republic", code: "DO", type: "country", iso3: "DOM" },
  { id: 64, name: "Ecuador", code: "EC", type: "country", iso3: "ECU" },
  { id: 65, name: "Egypt", code: "EG", type: "country", iso3: "EGY" },
  { id: 66, name: "El Salvador", code: "SV", type: "country", iso3: "SLV" },
  { id: 67, name: "Equatorial Guinea", code: "GQ", type: "country", iso3: "GNQ" },
  { id: 68, name: "Eritrea", code: "ER", type: "country", iso3: "ERI" },
  { id: 69, name: "Estonia", code: "EE", type: "country", iso3: "EST" },
  { id: 70, name: "Eswatini", code: "SZ", type: "country", iso3: "SWZ" },
  { id: 71, name: "Ethiopia", code: "ET", type: "country", iso3: "ETH" },
  { id: 72, name: "European Union", code: "EU", type: "country", iso3: "EUE" },
  { id: 73, name: "Falkland Islands (Malvinas)", code: "FK", type: "country", iso3: "FLK" },
  { id: 74, name: "Faroe Islands", code: "FO", type: "country", iso3: "FRO" },
  { id: 75, name: "Fiji", code: "FJ", type: "country", iso3: "FJI" },
  { id: 76, name: "Finland", code: "FI", type: "country", iso3: "FIN" },
  { id: 77, name: "France", code: "FR", type: "country", iso3: "FRA" },
  { id: 78, name: "French Guiana", code: "GF", type: "country", iso3: "GUF" },
  { id: 79, name: "French Polynesia", code: "PF", type: "country", iso3: "PYF" },
  { id: 80, name: "French Southern Territories", code: "TF", type: "country", iso3: "ATF" },
  { id: 81, name: "Gabon", code: "GA", type: "country", iso3: "GAB" },
  { id: 82, name: "Gambia", code: "GM", type: "country", iso3: "GMB" },
  { id: 83, name: "Georgia", code: "GE", type: "country", iso3: "GEO" },
  { id: 84, name: "Germany", code: "DE", type: "country", iso3: "DEU" },
  { id: 85, name: "Ghana", code: "GH", type: "country", iso3: "GHA" },
  { id: 86, name: "Gibraltar", code: "GI", type: "country", iso3: "GIB" },
  { id: 87, name: "Greece", code: "GR", type: "country", iso3: "GRC" },
  { id: 88, name: "Greenland", code: "GL", type: "country", iso3: "GRL" },
  { id: 89, name: "Grenada", code: "GD", type: "country", iso3: "GRD" },
  { id: 90, name: "Guadeloupe", code: "GP", type: "country", iso3: "GLP" },
  { id: 91, name: "Guam", code: "GU", type: "country", iso3: "GUM" },
  { id: 92, name: "Guatemala", code: "GT", type: "country", iso3: "GTM" },
  { id: 93, name: "Guernsey", code: "GG", type: "country", iso3: "GGY" },
  { id: 94, name: "Guinea", code: "GN", type: "country", iso3: "GIN" },
  { id: 95, name: "Guinea-Bissau", code: "GW", type: "country", iso3: "GNB" },
  { id: 96, name: "Guyana", code: "GY", type: "country", iso3: "GUY" },
  { id: 97, name: "Haiti", code: "HT", type: "country", iso3: "HTI" },
  { id: 98, name: "Heard Island and McDonald Islands", code: "HM", type: "country", iso3: "HMD" },
  { id: 99, name: "Holy See", code: "VA", type: "country", iso3: "VAT" },
  { id: 100, name: "Honduras", code: "HN", type: "country", iso3: "HND" },
  { id: 101, name: "China, Hong Kong Special Administrative Region", code: "HK", type: "country", iso3: "HKG" },
  { id: 102, name: "Hungary", code: "HU", type: "country", iso3: "HUN" },
  { id: 103, name: "Iceland", code: "IS", type: "country", iso3: "ISL" },
  { id: 104, name: "India", code: "IN", type: "country", iso3: "IND" },
  { id: 105, name: "Indonesia", code: "ID", type: "country", iso3: "IDN" },
  { id: 106, name: "Iran (Islamic Republic of)", code: "IR", type: "country", iso3: "IRN" },
  { id: 107, name: "Iraq", code: "IQ", type: "country", iso3: "IRQ" },
  { id: 108, name: "Ireland", code: "IE", type: "country", iso3: "IRL" },
  { id: 109, name: "Isle of Man", code: "IM", type: "country", iso3: "IMN" },
  { id: 110, name: "Israel", code: "IL", type: "country", iso3: "ISR" },
  { id: 111, name: "Italy", code: "IT", type: "country", iso3: "ITA" },
  { id: 112, name: "Jamaica", code: "JM", type: "country", iso3: "JAM" },
  { id: 113, name: "Japan", code: "JP", type: "country", iso3: "JPN" },
  { id: 114, name: "Jersey", code: "JE", type: "country", iso3: "JEY" },
  { id: 115, name: "Jordan", code: "JO", type: "country", iso3: "JOR" },
  { id: 116, name: "Kazakhstan", code: "KZ", type: "country", iso3: "KAZ" },
  { id: 117, name: "Kenya", code: "KE", type: "country", iso3: "KEN" },
  { id: 118, name: "Kiribati", code: "KI", type: "country", iso3: "KIR" },
  { id: 119, name: "Democratic People's Republic of Korea", code: "KP", type: "country", iso3: "PRK" },
  { id: 120, name: "Republic of Korea", code: "KR", type: "country", iso3: "KOR" },
  { id: 121, name: "Kuwait", code: "KW", type: "country", iso3: "KWT" },
  { id: 122, name: "Kyrgyzstan", code: "KG", type: "country", iso3: "KGZ" },
  { id: 123, name: "Lao People's Democratic Republic", code: "LA", type: "country", iso3: "LAO" },
  { id: 124, name: "Latvia", code: "LV", type: "country", iso3: "LVA" },
  { id: 125, name: "Lebanon", code: "LB", type: "country", iso3: "LBN" },
  { id: 126, name: "Lesotho", code: "LS", type: "country", iso3: "LSO" },
  { id: 127, name: "Liberia", code: "LR", type: "country", iso3: "LBR" },
  { id: 128, name: "Libya", code: "LY", type: "country", iso3: "LBY" },
  { id: 129, name: "Liechtenstein", code: "LI", type: "country", iso3: "LIE" },
  { id: 130, name: "Lithuania", code: "LT", type: "country", iso3: "LTU" },
  { id: 131, name: "Luxembourg", code: "LU", type: "country", iso3: "LUX" },
  { id: 132, name: "China, Macao Special Administrative Region", code: "MO", type: "country", iso3: "MAC" },
  { id: 133, name: "Madagascar", code: "MG", type: "country", iso3: "MDG" },
  { id: 134, name: "Malawi", code: "MW", type: "country", iso3: "MWI" },
  { id: 135, name: "Malaysia", code: "MY", type: "country", iso3: "MYS" },
  { id: 136, name: "Maldives", code: "MV", type: "country", iso3: "MDV" },
  { id: 137, name: "Mali", code: "ML", type: "country", iso3: "MLI" },
  { id: 138, name: "Malta", code: "MT", type: "country", iso3: "MLT" },
  { id: 139, name: "Marshall Islands", code: "MH", type: "country", iso3: "MHL" },
  { id: 140, name: "Martinique", code: "MQ", type: "country", iso3: "MTQ" },
  { id: 141, name: "Mauritania", code: "MR", type: "country", iso3: "MRT" },
  { id: 142, name: "Mauritius", code: "MU", type: "country", iso3: "MUS" },
  { id: 143, name: "Mayotte", code: "YT", type: "country", iso3: "MYT" },
  { id: 144, name: "Mexico", code: "MX", type: "country", iso3: "MEX" },
  { id: 145, name: "Micronesia (Federated States of)", code: "FM", type: "country", iso3: "FSM" },
  { id: 146, name: "Republic of Moldova", code: "MD", type: "country", iso3: "MDA" },
  { id: 147, name: "Monaco", code: "MC", type: "country", iso3: "MCO" },
  { id: 148, name: "Mongolia", code: "MN", type: "country", iso3: "MNG" },
  { id: 149, name: "Montenegro", code: "ME", type: "country", iso3: "MNE" },
  { id: 150, name: "Montserrat", code: "MS", type: "country", iso3: "MSR" },
  { id: 151, name: "Morocco", code: "MA", type: "country", iso3: "MAR" },
  { id: 152, name: "Mozambique", code: "MZ", type: "country", iso3: "MOZ" },
  { id: 153, name: "Myanmar", code: "MM", type: "country", iso3: "MMR" },
  { id: 154, name: "Namibia", code: "NA", type: "country", iso3: "NAM" },
  { id: 155, name: "Nauru", code: "NR", type: "country", iso3: "NRU" },
  { id: 156, name: "Nepal", code: "NP", type: "country", iso3: "NPL" },
  { id: 157, name: "Netherlands (Kingdom of the)", code: "NL", type: "country", iso3: "NLD" },
  { id: 158, name: "New Caledonia", code: "NC", type: "country", iso3: "NCL" },
  { id: 159, name: "New Zealand", code: "NZ", type: "country", iso3: "NZL" },
  { id: 160, name: "Nicaragua", code: "NI", type: "country", iso3: "NIC" },
  { id: 161, name: "Niger", code: "NE", type: "country", iso3: "NER" },
  { id: 162, name: "Nigeria", code: "NG", type: "country", iso3: "NGA" },
  { id: 163, name: "Niue", code: "NU", type: "country", iso3: "NIU" },
  { id: 164, name: "Norfolk Island", code: "NF", type: "country", iso3: "NFK" },
  { id: 165, name: "Northern Mariana Islands", code: "MP", type: "country", iso3: "MNP" },
  { id: 166, name: "Norway", code: "NO", type: "country", iso3: "NOR" },
  { id: 167, name: "Oman", code: "OM", type: "country", iso3: "OMN" },
  { id: 168, name: "Pakistan", code: "PK", type: "country", iso3: "PAK" },
  { id: 169, name: "Palau", code: "PW", type: "country", iso3: "PLW" },
  { id: 170, name: "State of Palestine", code: "PS", type: "country", iso3: "PSE" },
  { id: 171, name: "Panama", code: "PA", type: "country", iso3: "PAN" },
  { id: 172, name: "Papua New Guinea", code: "PG", type: "country", iso3: "PNG" },
  { id: 173, name: "Paraguay", code: "PY", type: "country", iso3: "PRY" },
  { id: 174, name: "Peru", code: "PE", type: "country", iso3: "PER" },
  { id: 175, name: "Philippines", code: "PH", type: "country", iso3: "PHL" },
  { id: 176, name: "Pitcairn", code: "PN", type: "country", iso3: "PCN" },
  { id: 177, name: "Poland", code: "PL", type: "country", iso3: "POL" },
  { id: 178, name: "Portugal", code: "PT", type: "country", iso3: "PRT" },
  { id: 179, name: "Puerto Rico", code: "PR", type: "country", iso3: "PRI" },
  { id: 180, name: "Qatar", code: "QA", type: "country", iso3: "QAT" },
  { id: 181, name: "North Macedonia", code: "MK", type: "country", iso3: "MKD" },
  { id: 182, name: "Romania", code: "RO", type: "country", iso3: "ROU" },
  { id: 183, name: "Russian Federation", code: "RU", type: "country", iso3: "RUS" },
  { id: 184, name: "Rwanda", code: "RW", type: "country", iso3: "RWA" },
  { id: 185, name: "Réunion", code: "RE", type: "country", iso3: "REU" },
  { id: 186, name: "Saint Barthélemy", code: "BL", type: "country", iso3: "BLM" },
  { id: 187, name: "Saint Helena", code: "SH", type: "country", iso3: "SHN" },
  { id: 188, name: "Saint Kitts and Nevis", code: "KN", type: "country", iso3: "KNA" },
  { id: 189, name: "Saint Lucia", code: "LC", type: "country", iso3: "LCA" },
  { id: 190, name: "Saint Martin (French part)", code: "MF", type: "country", iso3: "MAF" },
  { id: 191, name: "Saint Pierre and Miquelon", code: "PM", type: "country", iso3: "SPM" },
  { id: 192, name: "Saint Vincent and the Grenadines", code: "VC", type: "country", iso3: "VCT" },
  { id: 193, name: "Samoa", code: "WS", type: "country", iso3: "WSM" },
  { id: 194, name: "San Marino", code: "SM", type: "country", iso3: "SMR" },
  { id: 195, name: "Sao Tome and Principe", code: "ST", type: "country", iso3: "STP" },
  { id: 196, name: "Saudi Arabia", code: "SA", type: "country", iso3: "SAU" },
  { id: 197, name: "Senegal", code: "SN", type: "country", iso3: "SEN" },
  { id: 198, name: "Serbia", code: "RS", type: "country", iso3: "SRB" },
  { id: 199, name: "Seychelles", code: "SC", type: "country", iso3: "SYC" },
  { id: 200, name: "Sierra Leone", code: "SL", type: "country", iso3: "SLE" },
  { id: 201, name: "Singapore", code: "SG", type: "country", iso3: "SGP" },
  { id: 202, name: "Sint Maarten (Dutch part)", code: "SX", type: "country", iso3: "SXM" },
  { id: 203, name: "Slovakia", code: "SK", type: "country", iso3: "SVK" },
  { id: 204, name: "Slovenia", code: "SI", type: "country", iso3: "SVN" },
  { id: 205, name: "Solomon Islands", code: "SB", type: "country", iso3: "SLB" },
  { id: 206, name: "Somalia", code: "SO", type: "country", iso3: "SOM" },
  { id: 207, name: "South Africa", code: "ZA", type: "country", iso3: "ZAF" },
  { id: 208, name: "South Georgia and the South Sandwich Islands", code: "GS", type: "country", iso3: "SGS" },
  { id: 209, name: "South Sudan", code: "SS", type: "country", iso3: "SSD" },
  { id: 210, name: "Spain", code: "ES", type: "country", iso3: "ESP" },
  { id: 211, name: "Sri Lanka", code: "LK", type: "country", iso3: "LKA" },
  { id: 212, name: "Sudan", code: "SD", type: "country", iso3: "SDN" },
  { id: 213, name: "Suriname", code: "SR", type: "country", iso3: "SUR" },
  { id: 214, name: "Svalbard and Jan Mayen Islands", code: "SJ", type: "country", iso3: "SJM" },
  { id: 215, name: "Sweden", code: "SE", type: "country", iso3: "SWE" },
  { id: 216, name: "Switzerland", code: "CH", type: "country", iso3: "CHE" },
  { id: 217, name: "Syrian Arab Republic", code: "SY", type: "country", iso3: "SYR" },
  { id: 218, name: "Taiwan, Province of China", code: "TW", type: "country", iso3: "TWN" },
  { id: 219, name: "Tajikistan", code: "TJ", type: "country", iso3: "TJK" },
  { id: 220, name: "United Republic of Tanzania", code: "TZ", type: "country", iso3: "TZA" },
  { id: 221, name: "Thailand", code: "TH", type: "country", iso3: "THA" },
  { id: 222, name: "Timor-Leste", code: "TL", type: "country", iso3: "TLS" },
  { id: 223, name: "Togo", code: "TG", type: "country", iso3: "TGO" },
  { id: 224, name: "Tokelau", code: "TK", type: "country", iso3: "TKL" },
  { id: 225, name: "Tonga", code: "TO", type: "country", iso3: "TON" },
  { id: 226, name: "Trinidad and Tobago", code: "TT", type: "country", iso3: "TTO" },
  { id: 227, name: "Tunisia", code: "TN", type: "country", iso3: "TUN" },
  { id: 228, name: "Türkiye", code: "TR", type: "country", iso3: "TUR" },
  { id: 229, name: "Turkmenistan", code: "TM", type: "country", iso3: "TKM" },
  { id: 230, name: "Turks and Caicos Islands", code: "TC", type: "country", iso3: "TCA" },
  { id: 231, name: "Tuvalu", code: "TV", type: "country", iso3: "TUV" },
  { id: 232, name: "Uganda", code: "UG", type: "country", iso3: "UGA" },
  { id: 233, name: "Ukraine", code: "UA", type: "country", iso3: "UKR" },
  { id: 234, name: "United Arab Emirates", code: "AE", type: "country", iso3: "ARE" },
  { id: 235, name: "United Kingdom of Great Britain and Northern Ireland", code: "GB", type: "country", iso3: "GBR" },
  { id: 236, name: "United States Minor Outlying Islands", code: "UM", type: "country", iso3: "UMI" },
  { id: 237, name: "United States of America", code: "US", type: "country", iso3: "USA" },
  { id: 238, name: "Uruguay", code: "UY", type: "country", iso3: "URY" },
  { id: 239, name: "Uzbekistan", code: "UZ", type: "country", iso3: "UZB" },
  { id: 240, name: "Vanuatu", code: "VU", type: "country", iso3: "VUT" },
  { id: 241, name: "Venezuela (Bolivarian Republic of)", code: "VE", type: "country", iso3: "VEN" },
  { id: 242, name: "Viet Nam", code: "VN", type: "country", iso3: "VNM" },
  { id: 243, name: "British Virgin Islands", code: "VG", type: "country", iso3: "VGB" },
  { id: 244, name: "United States Virgin Islands", code: "VI", type: "country", iso3: "VIR" },
  { id: 245, name: "Wallis and Futuna Islands", code: "WF", type: "country", iso3: "WLF" },
  { id: 246, name: "Western Sahara", code: "EH", type: "country", iso3: "ESH" },
  { id: 247, name: "Yemen", code: "YE", type: "country", iso3: "YEM" },
  { id: 248, name: "Zambia", code: "ZM", type: "country", iso3: "ZMB" },
  { id: 249, name: "Zimbabwe", code: "ZW", type: "country", iso3: "ZWE" },
  { id: 250, name: "Åland Islands", code: "AX", type: "country", iso3: "ALA" },
  { id: 251, name: "World", code: "🌐", type: "global", iso3: "🌐" },
  { id: 252, name: "Africa", code: "🗺", type: "region", iso3: "" },
  { id: 253, name: "Americas", code: "🗺", type: "region", iso3: "" },
  { id: 254, name: "Asia", code: "🗺", type: "region", iso3: "" },
  { id: 255, name: "Europe", code: "🗺", type: "region", iso3: "" },
  { id: 256, name: "Oceania", code: "🗺", type: "region", iso3: "" },
  { id: 257, name: "Northern Africa", code: "🗺", type: "sub_region", iso3: "" },
  { id: 258, name: "Sub-Saharan Africa", code: "🗺", type: "sub_region", iso3: "" },
  { id: 259, name: "Latin America and the Caribbean", code: "🗺", type: "sub_region", iso3: "" },
  { id: 260, name: "Northern America", code: "🗺", type: "sub_region", iso3: "" },
  { id: 261, name: "Central Asia", code: "🗺", type: "sub_region", iso3: "" },
  { id: 262, name: "Eastern Asia", code: "🗺", type: "sub_region", iso3: "" },
  { id: 263, name: "South-eastern Asia", code: "🗺", type: "sub_region", iso3: "" },
  { id: 264, name: "Southern Asia", code: "🗺", type: "sub_region", iso3: "" },
  { id: 265, name: "Western Asia", code: "🗺", type: "sub_region", iso3: "" },
  { id: 266, name: "Eastern Europe", code: "🗺", type: "sub_region", iso3: "" },
  { id: 267, name: "Northern Europe", code: "🗺", type: "sub_region", iso3: "" },
  { id: 268, name: "Southern Europe", code: "🗺", type: "sub_region", iso3: "" },
  { id: 269, name: "Western Europe", code: "🗺", type: "sub_region", iso3: "" },
  { id: 270, name: "Australia and New Zealand", code: "🗺", type: "sub_region", iso3: "" },
  { id: 271, name: "Melanesia", code: "🗺", type: "sub_region", iso3: "" },
  { id: 272, name: "Micronesia", code: "🗺", type: "sub_region", iso3: "" },
  { id: 273, name: "Polynesia", code: "🗺", type: "sub_region", iso3: "" },
  { id: 274, name: "Eastern Africa", code: "🗺", type: "intermediat_region", iso3: "" },
  { id: 275, name: "Middle Africa", code: "🗺", type: "intermediat_region", iso3: "" },
  { id: 276, name: "Southern Africa", code: "🗺", type: "intermediat_region", iso3: "" },
  { id: 277, name: "Western Africa", code: "🗺", type: "intermediat_region", iso3: "" },
  { id: 278, name: "Caribbean", code: "🗺", type: "intermediat_region", iso3: "" },
  { id: 279, name: "Central America", code: "🗺", type: "intermediat_region", iso3: "" },
  { id: 280, name: "South America", code: "🗺", type: "intermediat_region", iso3: "" },
  { id: 281, name: "Alabama", code: "AL", type: "state", iso3: "ALA" },
  { id: 282, name: "Alaska", code: "AK", type: "state", iso3: "ALK" },
  { id: 283, name: "Arizona", code: "AZ", type: "state", iso3: "ARZ" },
  { id: 284, name: "Arkansas", code: "AR", type: "state", iso3: "ARK" },
  { id: 285, name: "California", code: "CA", type: "state", iso3: "CAL" },
  { id: 286, name: "Colorado", code: "CO", type: "state", iso3: "COL" },
  { id: 287, name: "Connecticut", code: "CT", type: "state", iso3: "CON" },
  { id: 288, name: "Delaware", code: "DE", type: "state", iso3: "DEL" },
  { id: 289, name: "Florida", code: "FL", type: "state", iso3: "FLA" },
  { id: 290, name: "Georgia", code: "GA", type: "state", iso3: "GEO" },
  { id: 291, name: "Hawaii", code: "HI", type: "state", iso3: "HAW" },
  { id: 292, name: "Idaho", code: "ID", type: "state", iso3: "IDA" },
  { id: 293, name: "Illinois", code: "IL", type: "state", iso3: "ILL" },
  { id: 294, name: "Indiana", code: "IN", type: "state", iso3: "IND" },
  { id: 295, name: "Iowa", code: "IA", type: "state", iso3: "IOW" },
  { id: 296, name: "Kansas", code: "KS", type: "state", iso3: "KAN" },
  { id: 297, name: "Kentucky", code: "KY", type: "state", iso3: "KEN" },
  { id: 298, name: "Louisiana", code: "LA", type: "state", iso3: "LOU" },
  { id: 299, name: "Maine", code: "ME", type: "state", iso3: "MAI" },
  { id: 300, name: "Maryland", code: "MD", type: "state", iso3: "MAR" },
  { id: 301, name: "Massachusetts", code: "MA", type: "state", iso3: "MAS" },
  { id: 302, name: "Michigan", code: "MI", type: "state", iso3: "MIC" },
  { id: 303, name: "Minnesota", code: "MN", type: "state", iso3: "MIN" },
  { id: 304, name: "Mississippi", code: "MS", type: "state", iso3: "MIS" },
  { id: 305, name: "Missouri", code: "MO", type: "state", iso3: "MO" },
  { id: 306, name: "Montana", code: "MT", type: "state", iso3: "MON" },
  { id: 307, name: "Nebraska", code: "NE", type: "state", iso3: "NEB" },
  { id: 308, name: "Nevada", code: "NV", type: "state", iso3: "NEV" },
  { id: 309, name: "New Hampshire", code: "NH", type: "state", iso3: "NHA" },
  { id: 310, name: "New Jersey", code: "NJ", type: "state", iso3: "NJE" },
  { id: 311, name: "New Mexico", code: "NM", type: "state", iso3: "NMX" },
  { id: 312, name: "New York", code: "NY", type: "state", iso3: "NYK" },
  { id: 313, name: "North Carolina", code: "NC", type: "state", iso3: "NCR" },
  { id: 314, name: "North Dakota", code: "ND", type: "state", iso3: "NDK" },
  { id: 315, name: "Ohio", code: "OH", type: "state", iso3: "OHI" },
  { id: 316, name: "Oklahoma", code: "OK", type: "state", iso3: "OKL" },
  { id: 317, name: "Oregon", code: "OR", type: "state", iso3: "ORE" },
  { id: 318, name: "Pennsylvania", code: "PA", type: "state", iso3: "PEN" },
  { id: 319, name: "Rhode Island", code: "RI", type: "state", iso3: "RHI" },
  { id: 320, name: "South Carolina", code: "SC", type: "state", iso3: "SCR" },
  { id: 321, name: "South Dakota", code: "SD", type: "state", iso3: "SDK" },
  { id: 322, name: "Tennessee", code: "TN", type: "state", iso3: "TEN" },
  { id: 323, name: "Texas", code: "TX", type: "state", iso3: "TEX" },
  { id: 324, name: "Utah", code: "UT", type: "state", iso3: "UTA" },
  { id: 325, name: "Vermont", code: "VT", type: "state", iso3: "VER" },
  { id: 326, name: "Virginia", code: "VA", type: "state", iso3: "VIR" },
  { id: 327, name: "Washington", code: "WA", type: "state", iso3: "WAS" },
  { id: 328, name: "West Virginia", code: "WV", type: "state", iso3: "UWV" },
  { id: 329, name: "Wisconsin", code: "WI", type: "state", iso3: "WIS" },
  { id: 330, name: "Wyoming", code: "WY", type: "state", iso3: "WYO" },
  { id: 331, name: "International", code: "🌐", type: "country", iso3: "🌐" }
].sort((a, b) => a.name.localeCompare(b.name));

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const type = searchParams.get('type');
    
    let filteredJurisdictions = HARDCODED_JURISDICTIONS;
    
    // Filter by type if specified
    if (type) {
      filteredJurisdictions = HARDCODED_JURISDICTIONS.filter(
        jurisdiction => jurisdiction.type === type
      );
    }

    // Return the jurisdictions list
    return NextResponse.json({
      jurisdictions: filteredJurisdictions,
      count: filteredJurisdictions.length
    });

  } catch (error) {
    console.error("Jurisdictions API route error:", error);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}